DEFAULT_SIZE = 3
SIZE_RESTRICTION = 8
DEFAULT_LAYER_COUNT = 10
LAYER_RESTRICTION = 20
DISTURBANCE_PROBABILITY = 0.50
DISTURBANCE_BOUNDS = (-10, 10)
QUBIT_DISTURBANCE_PROBABILITY = 0.4
ROTATION_PROBABILITY = 0.1




